<?php

/**
 * Implements hook_install().
 */
function moderation_dropbutton_install() {
  // Set weight of module to run after workbench_moderation.
  db_update('system')
    ->fields(array('weight' => 6))
    ->condition('name', 'moderation_dropbutton')
    ->execute();
}

/**
 * Implements hook_uninstall().
 */
function moderation_dropbutton_uninstall() {
  db_delete('variable')
    ->condition('name', db_like('moderation_dropbutton_') . '%', 'LIKE')
    ->execute();
}
